# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

#      - name: Generate Version
#        uses: HardNorth/github-version-generate@v1.1.1
#        with:
#          version-source: file
#          version-file: build.gradle
#          version-file-extraction-pattern: "(?<=version = ').+(?<=')"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: set permissions
        run: chmod u+x ./gradlew

      - name: build-gradle
        run: ./gradlew build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/libs/*.jar'
          tag: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
